<?php include './header.php';?>

<div class="section wellbeing-a">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 pull-right margin70">
                <h2 class="section-heading">Gaining insights from daily routines</h2>
                <p class="lead margin70">Simple weekday practices create a rhythm for our daily life. Each day is filled with these simple actions, like eating breakfast, buying groceries or reading a newspaper. While being an integral part of our life, daily routines have a much bigger role to play. Combined, they can give valuable insights into our
                physical and mental wellbeing.</p>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-5 padding200">
            <h4>Wellbeing</h4>
            <h2 class="section-heading">Living environment</h2>
            <h5>Living environment not only has a profound impact on us, it can also shed light on
            our daily life. In just a matter of time our homes will be equipped with a variety of
            sensor technology, making it possible to capture every step of our daily life in real
            time.
            </h5>
            <h5>
            Together with sophisticated algorithms, data generated by multiple sensors makes it
            possible to assess daily activities in person’s actual environment and evaluate
            possible changes in her activities.
            </h5>
            <h5>
            These changes can be a signal of a weakening muscle power, early stage of
            dementia or depression. Capturing adverse changes as early as possible, gives an
            opportunity to start treatment much earlier than it is done today, increasing treatment
            efficiency and prolonging its lasting effect.
            </h5>
        </div>     
        <div class="col-sm-6 col-sm-offset-1 padding0">
            <img class="margin0 right-half" src="./img/10.jpg">  
        </div>          
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-6 padding0">
            <img class="right-half" src="./img/11.jpg">  
        </div>   
        <div class="col-sm-5 col-sm-offset-1 padding190">
            <h2 class="section-heading">Ageing with vitality</h2>
            <h5>Golden years are often seen through the prism of disability,
                forgetting about all the joy they bring. Providing loving support
                and preserving the sense of independence is what we aim for.
            </h5>
            <h5>
                The quality of life improves when the person can act
                autonomously within her familiar surroundings. It gives her a
                sense of security and independence. Being active and motivated
                is the key to vital ageing.
            </h5>
            <h5>
                Early recognition of various disabilities and cognitive disorders
                can pave way to more accurate treatment and have remarkable
                influence on the lives of people, and even increase the number of
                active and independent days of life.
            </h5>
            <h5>
                As a result, social- and healthcare system will greatly benefit by
                decreasing elderly care costs and creating new efficient services
                for their customers.
            </h5>
        </div>     
    </div>
</div>
<div class="intro-section bg-gray">
    <div class="center-container"> 
        <h2>Wellbeing analytics methology</h2>
        <h4>Wellbeing Analytics Platform is employing the methodology of the
            International Classification of Functioning, Disability and Health (ICF) by WHO and the Life-Based Design.
        </h4>            
    </div>
</div>
<div class="intro-section bg-gray paddingtop0">
    <div class="row margin40">
        <div class="col-sm-6">
            <div class="square text-left">
                <h2>ICF Classification</h2>
                <h4>ICF creates a framework allowing all conditions to be
                    compared using a common metric. Furthermore, ICF
                    examines functioning and performance of people as a
                    dynamic interaction between the individual, the activity
                    and the environment. Daily routines are illustrated through
                    activity typologies. A single activity typology is created by
                    mapping ICF classes to individual forms of life (FoL).
                    Some examples of an FoL could be “sleeping”, “cooking
                    a meal” or “buying groceries”.
                </h4> 
            </div>           
        </div>
        <div class="col-sm-6">
            <div class="square text-left">
                <h2>Life-based design</h2>
                <h4>The FoL is a basic tool used in the framework of Life-Based
                    Design. Its main idea is to take analysis of human life as the
                    ground concept for designing technology-supported services.
                    The form of life is influenced by environmental factors and
                    person typology, comprising of socio-cultural, biological,
                    psychological attributes. Through understanding the factors
                    that influence the FoL, we can identify if any adverse changes
                    are happening and point out the reasons why they could have
                    happened.
                </h4>        
            </div>    
        </div>      
    </div>
</div>
<div class="intro-section bg-gray paddingtop0">
    <div class="center-container">
        <div class="">
        <h2 class="section-heading">Our services</h2>
        <h4 class="text-center">We offer variety of services designed to make your business more powerful and effective.
        </h4>
        <button type="button" class="message-btn">Learn more</button>
        </div>
         
    </div>
</div>

<?php include './footer.php';?>